import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import Navbar from "../components/custom/navbar";
import {poppins, b612, allan} from '@/lib/fonts';
import { Toaster } from "@/components/ui/toaster"


const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Geverel Software",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${b612} ${poppins} ${allan}`}>
      <Navbar/>
      {children}
      <Toaster />
      </body>
    </html>
  );
}
